export const reducerCases = {
  TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
  TOGGLE_SIGNUP_MODAL: "TOGGLE_SIGNUP_MODAL",
  CLOSE_AUTH_MODEL: "CLOSE_AUTH_MODEL",
  SET_USER: "SET_USER",
  SWITCH_MODE: "SWITCH_MODE",
};
