import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <>
          <div className={`mb-auto w-full mx-auto`}>{children}</div>
          <Footer />
        </>
      </body>
    </html>
  );
}
